# refrences:
# https://dev.to/tngeene/automating-django-deployment-workflow-with-github-actions-2i1o

name: Deploy Django backend to OVH VPS on merge

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
      # don't run locally
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PROD_DB: ${{ secrets.POSTGRES_PROD_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.SERVER_DEPLOY_PORT }}
          allenvs: true
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/312coders/312coders.git
            cd backend
            docker compose down
            docker compose up --build -d